spring.application.name=franchise
server.port=${SERVER_PORT:8080}
spring.tz=${TZ:America/Bogota}
server.error.include-message=always
server.error.include-binding-errors=always
server.servlet.context-path=/franchise-api/v1
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${POSTGRE_URL:jdbc:postgresql://localhost:5432/franchise_db}
spring.datasource.username=${POSTGRE_USERNAME:postgres}
spring.datasource.password=${POSTGRE_PASSWORD:pass}
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
server.error.include-stacktrace=never
spring.data.jdbc.repositories.enabled=false
spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false